apiVersion: apps/v1
kind: Deployment
metadata:
  name: goo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goo
  template:
    metadata:
      labels:
        app: goo
    spec:
      containers:
      - image: okteto.dev/goo:latest
        name: goo
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "ed0251a3-1f5d-464d-9332-21d0ac2fafa7"
        - name: Vless_Path
          value: "/s233Smm"
        - name: Vmess_UUID
          value: "ed0251a3-1f5d-464d-9332-21d0ac2fafa7"
        - name: Vmess_Path
          value: "/s244Smm"
        - name: Share_Path
          value: "/share233"
